server:
  port: 8182

spring:
  application:
    name: feign-demo
  cloud:
    config:
      uri: ${config.server.uri:http://localhost:8888}
  zipkin:
    base-url: http://localhost:9966
  sleuth:
    enabled: true
    sampler:
      percentage: 1

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Increase hystrix thread pool
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 100
  threadpool:
    default:
      coreSize: 25
      maxQueueSize: 500

# Enable admin endpoints
endpoints:
  metrics:
    enabled: true
    sensitive: false
  dump:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  trace:
    enabled: true
    sensitive: false
  heapdump:
    enabled: true
    sensitive: false

# Enable hystrix support for feign
feign:
  hystrix:
    enabled: true

